frontends/Ecommerce.WebUI/Areas/Admin/Controllers/ProductDetailController.cs
using Ecommerce.DtoLayer.CatalogDtos.ProductDetailDtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Ecommerce.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/ProductDetail")]
    public class ProductDetailController : Controller
    {
       

        private readonly IHttpClientFactory _httpClientFactory;

        public ProductDetailController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
   

        [Route("UpdateProductDetail/{id}")]
        [HttpGet]
        public async Task<IActionResult> UpdateProductDetail(string id)
        {
            ViewBag.v0 = "Home Page";
            ViewBag.v1 = "ProductDetails";
            ViewBag.v2 = "Update ProductDetail";
            ViewBag.v3 = "ProductDetail Operations";
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("http://localhost:7220/api/ProductDetails/GetProductDetailByProductId?id=" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<UpdateProductDetailDto>(jsonData);
                return View(values);
            }
            return View();
        }

        [Route("UpdateProductDetail/{id}")]
        [HttpPost]
        public async Task<IActionResult> UpdateProductDetail(UpdateProductDetailDto updateProductDetailDto)
        {

            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(updateProductDetailDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync("http://localhost:7220/api/ProductDetails/", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("ProductListWithCategory", "Product", new { area = "Admin" });
            }
            return View();
        }

    }
}

frontends/Ecommerce.WebUI/Controllers/ProductListController.cs
using Ecommerce.DtoLayer.ReviewDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Ecommerce.WebUI.Controllers
{
    public class ProductListController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public ProductListController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index(string id)
        {
            @ViewBag.directory1 = "Home Page";
            @ViewBag.directory2 = "Products";
            @ViewBag.directory3 = "Product List";
            ViewBag.i = id;
            return View();
        }

        public IActionResult ProductDetail(string id)
        {
            @ViewBag.directory1 = "Home Page";
            @ViewBag.directory2 = "Products";
            @ViewBag.directory3 = "Product List";
            ViewBag.x = id;
            return View();
        }

        [HttpGet]
        public IActionResult AddComment()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(CreateReviewDto createReviewDto)
        {
            createReviewDto.ImageUrl = "test";
            createReviewDto.Rating = 5;
            createReviewDto.CreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            createReviewDto.Status = false;
            createReviewDto.ProductId = "68f41aa07438fb5ca208b42d";
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(createReviewDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PostAsync("https://localhost:7252/api/Reviews", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index", "Default");
            }
            return View();
        }

    }
}

frontends/Ecommerce.WebUI/Views/ProductList/AddComment.cshtml
@using Ecommerce.WebUI.Services.LocalizationServices
@inject ILocalizationService localizer
<h4 class="mb-4">@localizer.GetLocalizeString("Leave a review")</h4>
    <small>@localizer.GetLocalizeString("Your email address will not be published. Required fields are marked") *</small>
    <div class="d-flex my-3">
        <p class="mb-0 mr-2">@localizer.GetLocalizeString("Your Rating") * :</p>
        <div class="text-primary">
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
        </div>
    </div>
    <form method="post" asp-action="AddComment" asp-controller="ProductList">
       
        <div class="form-group">
            <label for="name">@localizer.GetLocalizeString("Your Name") *</label>
            <input type="text" class="form-control" name="NameSurname">
        </div>
        <div class="form-group">
            <label for="email">@localizer.GetLocalizeString("Your Email") *</label>
            <input type="email" class="form-control"  name="Email">
        </div>
        <div class="form-group">
            <label for="message">@localizer.GetLocalizeString("Your Review") *</label>
            <textarea cols="30" rows="5" class="form-control" name="ReviewDetail"></textarea>
        </div>
        <div class="form-group mb-0">
            <input type="submit" value=@localizer.GetLocalizeString("Leave Your Review") class="btn btn-primary px-3">
        </div>
    </form>
</div>

frontends/Ecommerce.WebUI/Views/ProductList/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/UILayout/_UILayout.cshtml";
}


<div class="container-fluid">
    <div class="row px-xl-5">
     
        <div class="col-lg-3 col-md-4">
    
            @await Component.InvokeAsync("_ProductListPriceFilterComponentPartial")

            @await Component.InvokeAsync("_ProductListColorFilterComponentPartial")

            @await Component.InvokeAsync("_ProductListSizeFilterComponentPartial")
   
        </div>
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">

                @await Component.InvokeAsync("_ProductListSortingComponentPartial")

                @await Component.InvokeAsync("_ProductListComponentPartial", new {id=ViewBag.i})

                @await Component.InvokeAsync("_ProductListPaginationComponentPartial")

               
            </div>
        </div>
    </div>
</div>

frontends/Ecommerce.WebUI/Views/ProductList/ProductDetail.cshtml
@using Ecommerce.WebUI.Services.LocalizationServices
@inject ILocalizationService localizer
@{
    ViewData["Title"] = "ProductDetail";
    Layout = "~/Views/UILayout/_UILayout.cshtml";
}


<div class="container-fluid pb-5">
    <div class="row px-xl-5">

        @await Component.InvokeAsync("_ProductDetailImageSliderComponentPartial", new { id = ViewBag.x })

        @await Component.InvokeAsync("_ProductDetailFeatureComponentPartial",new {id = ViewBag.x})
      
    </div>
    <div class="row px-xl-5">
        <div class="col">
            <div class="bg-light p-30">
                <div class="nav nav-tabs mb-4">
                    <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">@localizer.GetLocalizeString("Description")</a>
                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">@localizer.GetLocalizeString("Information")</a>
                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">@localizer.GetLocalizeString("Reviews") (0)</a>
                </div>
                <div class="tab-content">

                    @await Component.InvokeAsync("_ProductDetailDescriptionComponentPartial", new {id = ViewBag.x} )

                    @await Component.InvokeAsync("_ProductDetailInformationComponentPartial", new { id = ViewBag.x })

                    @await Component.InvokeAsync("_ProductDetailReviewComponentPartial", new { id = ViewBag.x })
                    
                </div>
            </div>
        </div>
    </div>
</div>